export { HomePage } from './HomePage';
export { TokenPage } from './TokenPage';
export { CreatePage } from './CreatePage';
export { ProfilePage } from './ProfilePage';
export { RoyaltiesPage} from './RoyaltiesPage';
export { SellTokenPage } from './SellTokenPage';
export { CollectionPage } from './CollectionPage';
export { CollectionEditPage } from './CollectionEditPage';
export { AccountSettingsPage } from './AccountSettingsPage';
export { CreateCollectionPage } from './CreateCollectionPage';