export const routePaths = {
    
    home: "/",
    login: "/login",
    ledger: "/ledger",
    create: '/create',
    explore: '/explore',
    account: '/account',
    rankings: "/rankings",
    royalties: "/royalties",
    marketplace: '/marketplace',
    walletconnect: "/walletconnect",
    stats: '/admin/stats',
    profile: '/profile/:walletAddress',
    accountSettings: '/account/settings',
    collectionCreate: "/collection/create",
    collection: "/collection/:collectionId",
    freeMintCollection: "/collection/1852-568e49",
    token: "/token/:collectionId/:tokenNonce",
    collectionRegister: "/collection/register",
    resources: "https://erdseanft.gitbook.io/docs/",
    collectionEdit: '/collection/:collectionId/edit',
    sellToken: "/token/:walletAddress/:collectionId/:tokenNonce/sell",
    unlistedToken: "/token/:walletAddress/:collectionId/:tokenNonce",
    dao: "/dao",
    rewards: "/rewards",
    confirmation: "/confirmation/:action/:collectionId/:tokenNonce",
};