on:
  push:
    tags:
      - v0.*.*
env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  IMAGE: youbei-webapp
  SERVICE: youbei-webapp
  PROJECT_ID: youbei-339521
  REGISTRY_HOSTNAME: gcr.io
  HTTP_PORT: 5000
  HTTP_PORT_EXPOSE: 5000
  GOPRIVATE: "https://github.com/ENFT-DAO"
  REPO_TOKEN: ${{ secrets.REPO_TOKEN}}
jobs:
  deploy:
    runs-on: dev
    name: deploy
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/232956162006/locations/global/workloadIdentityPools/dev-youbei-github/providers/dev-github-provider'
          service_account: 'cloudrun@youbei-339521.iam.gserviceaccount.com'
      # - name: gcloud
      #   uses: google-github-actions/setup-gcloud@v0
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker
      - name: Build
        run: |
          export HOME=/home/amir
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          docker system prune -f
          docker build -t "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$TAG"  \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" -f ./DockerfileMain .
            
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker push "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$TAG"
          docker rmi -f $IMAGE:latest
          docker tag "$REGISTRY_HOSTNAME"/"$PROJECT_ID"/"$IMAGE":"$TAG" $IMAGE:latest
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{env.SERVICE}}
          image: ${{ env.REGISTRY_HOSTNAME}}/${{env.PROJECT_ID}}/${{env.IMAGE}}:${{ env.RELEASE_VERSION }}
      